const ACTION_SET_USER = 'USER_SET';
const ACTION_SIGN_UP = 'USER_SIGN_UP';
const ACTION_SIGN_IN = 'USER_SIGN_IN';
const ACTION_SIGN_OUT = 'USER_SIGN_OUT';

export {
    ACTION_SET_USER,
    ACTION_SIGN_UP,
    ACTION_SIGN_IN,
    ACTION_SIGN_OUT
};